#version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
    env_file: .env
    volumes:
      - ./config/:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/public/icons:/app/public/icons
    environment:
      PUID: $PUID
      PGID: $PGID
    restart: always
