---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services
#env_file: ".env"

- Machine Information:
    - Machine Info:
        icon: glances-light.png
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
            username: "{{HOMEPAGE_VAR_GLANCES_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GLANCES_SECRET}}"
            version: 4
            metric: info

    - CPU Usage:  
        icon: amd-light.png
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
            username: "{{HOMEPAGE_VAR_GLANCES_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GLANCES_SECRET}}"
            version: 4
            metric: cpu

    - Memory Usage:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
            username: "{{HOMEPAGE_VAR_GLANCES_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GLANCES_SECRET}}"
            metric: memory
            version: 4

    - Network Usage:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
            username: "{{HOMEPAGE_VAR_GLANCES_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GLANCES_SECRET}}"
            metric: network:vmbr0
            version: 4
    - Computer Temperature:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
            username: "{{HOMEPAGE_VAR_GLANCES_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GLANCES_SECRET}}"
            version: 4
            metric: sensor:Sensor 1
    - Processes:
        widget:
            type: glances
            url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
            username: "{{HOMEPAGE_VAR_GLANCES_USERNAME}}"
            password: "{{HOMEPAGE_VAR_GLANCES_SECRET}}"
            version: 4
            metric: process

- Calendar:
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: sunday
            showTime: true
            timezone: America/Los_Angeles
            integrations:
                - type: ical
                  url: "{{HOMEPAGE_VAR_CALENDAR_URL}}"
                  color: green

            # Holiday ical
                # - type: ical
                #   url: https://calendar.google.com/calendar/ical/en.canadian%23holiday%40group.v.calendar.google.com/public/basic.ics
                #   color: green
    - Agenda:
        widget:
            type: calendar
            view: agenda
            showTime: true 
            previousDays: 3
            integrations: 
                - type: ical
                  url: "{{HOMEPAGE_VAR_CALENDAR_URL}}"
                  color: green

- Entertainment:
    - Youtube:
        href: "https://youtube.com"
        icon: youtube.png

    - Netflix:
        href: "https://netflix.com"
        icon: netflix.png

    # - Disney Plus:
    #     href: "https://disneyplus.com"
    #     icon: disney-plus-light.png

- Social Media:
    - Instagram:
        href: "https://instagram.com"
        icon: instagram.png

    - Facebook:
        href: "https://facebook.com"
        icon: facebook.png

- Google and Developer:
    - Google Drive:
        href: "https://drive.google.com"   
        icon: google-drive.png 
    
    - Gmail:
        href: "https://mail.google.com"
        icon: gmail.png

    - Github:
        href: "https://github.com"
        icon: github-light.png


- Virtualization:
    - Proxmox:
        icon: proxmox.png
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: Hypervisor Hosting VMs
        siteMonitor: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        statusStyle: "dot"
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"
            
- Storage:
    - TruNAS:
        icon: truenas.png
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        statusStyle: "dot"
        ### For truenas API information. Will cause error if VM is shutdown
        # widget:
        #     type: truenas
        #     url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
            
        #     key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
        #     enablePools: true
        #     nasType: core
- Networking:
    - HP-2530-24 POE Switch:
        description: "Basement HP Switch"
        icon: hp.png
        href: "{{HOMEPAGE_VAR_HP_BASEMENT_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_HP_BASEMENT_URL}}"
        statusStyle: "dot"

- Camera Services:
    - iSpy Camera NVR:
        icon: ispy.png
        href: "{{HOMEPAGE_VAR_ISPY_URL}}"
        description: iSpy NVR Software
        siteMonitor: "{{HOMEPAGE_VAR_ISPY_URL}}"
        statusStyle: "dot"

    - Hikvision Camera:
        icon: hikvision.png
        href: "{{HOMEPAGE_VAR_HIKVISION_URL}}"
        description: Hikvision Home Camera
        siteMonitor: "{{HOMEPAGE_VAR_HIKVISION_URL}}"
        statusStyle: "dot"

    - Axis Camera:
        icon: axis.png
        href: "{{HOMEPAGE_VAR_AXIS_URL}}"
        description: Axis Home Camera
        siteMonitor: "{{HOMEPAGE_VAR_AXIS_URL}}"
        statusStyle: "dot"

