---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Homelab Homepage

theme: dark
color: gray

background:
  image: /icons/rx7.jpg
  brightness: 100
  opacity: 10

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: "{{HOMEPAGE_VAR_FINNHUB_KEY}}"

layout:
  Machine Information:
    style: row
    columns: 3
  Calendar:
    style: row
    columns: 2
    
