---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Homelab Homepage

theme: dark
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Machine Information:
    style: row
    columns: 3
  Calendar:
    style: row
    columns: 2
    